language: swift # or objective-c
osx_image: xcode9.1

before_install:
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - xcodebuild -scheme Runtime -workspace RuntimeDemo.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test

after_success:
  - bash <(curl -s https://codecov.io/bash) -t b950ada7-944f-4d80-9474-78be452bb8d5 -J 'Runtime'
